name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python 3.9
        run: |
          sudo apt update
          sudo apt install -y python3.9 python3.9-venv python3.9-dev
          sudo ln -sf /usr/bin/python3.9 /usr/bin/python

      - name: Instalar AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.138.0

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build aplicação
        run: sam build

      - name: Deploy aplicação
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name unicarioca-202501 \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --resolve-s3