name: Deploy SAM Application

on:
  push:
    branches:
      #- main informe a branch que ira disparar de forma automatica o pipeline

jobs:
  deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.138.0

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # cadastre o acess key no github secrets visando proteçao deste dado sensivel
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # cadastre o secret key no github secrets visando proteçao deste dado sensivel
          aws-region: us-east-1

      - name: Build aplicação
        run: sam build

      - name: Deploy aplicação
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name unicarioca-202501 \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --resolve-s3