name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar AWS CLI
        uses: aws-actions/setup-aws-cli@v2

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.138.0

      - name: Build da aplicação
        run: sam build

      - name: Deploy da aplicação
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name unicarioca-202501 --capabilities CAPABILITY_IAM --region us-east-1