name: Deploy SAM Application

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Build & Deploy SAM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: latest

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build SAM
        run: sam build

      - name: Validate SAM template
        run: sam validate

      - name: Deploy aplicação SAM
        run: |
          sam deploy \
            --stack-name unicarioca-202501 \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --region us-east-1 \
            --resolve-s3
